// Astro Content Collections schema for Second Spring Club.
//
// Three collections:
//   products  — one per Amazon product, generated by scout/generate.py
//   pillars   — long-form authority pages (hand-edited)
//   articles  — supporting Q&A and how-to content
//
// All three use Markdown with consistent frontmatter so listing pages
// can mix them safely.

import { defineCollection, z } from 'astro:content';

const products = defineCollection({
  type: 'content',
  schema: z.object({
    asin: z.string(),
    title: z.string(),
    seoTitle: z.string().optional().default(''),
    metaDescription: z.string().optional().default(''),
    // Card-level display (Pinterest-friendly short variants).
    // cardTitle overrides the long SEO title on listing grids.
    // cardPick is a one-line "why we picked it" shown under the card title.
    cardTitle: z.string().optional().default(''),
    cardPick: z.string().optional().default(''),
    category: z.string(),
    price: z.number().nullable().optional(),
    rating: z.number().nullable().optional(),
    reviewCount: z.number().nullable().optional(),
    bsr: z.number().nullable().optional(),
    commissionPerSale: z.number().optional().default(0),
    score: z.number().optional().default(0),
    imageUrl: z.string().optional().default(''),
    affiliateUrl: z.string(),
    isPrime: z.boolean().optional().default(false),
    status: z.enum(['draft', 'in_review', 'published']).default('draft'),
    firstSeen: z.string().optional().default(''),
    lastSeen: z.string().optional().default(''),
    tags: z.array(z.string()).optional().default([]),
    imageFlagged: z.boolean().optional().default(false),
  }),
});

const pillars = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    metaDescription: z.string(),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date().optional(),
    heroImage: z.string().optional(),
    excerpt: z.string(),
    targetKeyword: z.string(),
    relatedProducts: z.array(z.string()).optional().default([]),  // ASIN list
    status: z.enum(['draft', 'in_review', 'published']).default('draft'),
    tags: z.array(z.string()).optional().default([]),
  }),
});

const articles = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    metaDescription: z.string(),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date().optional(),
    heroImage: z.string().optional(),
    excerpt: z.string(),
    pillarSlug: z.string().optional(),  // which pillar this supports
    relatedProducts: z.array(z.string()).optional().default([]),
    status: z.enum(['draft', 'in_review', 'published']).default('draft'),
    tags: z.array(z.string()).optional().default([]),
  }),
});

export const collections = {
  products,
  pillars,
  articles,
};
